name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
#     - name: Set up Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

#     - name: Run the tests and generate coverage report
#       run: npm test -- --coverage

#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v3

#     - name: Build & Test
#       run: |
#         npm run build
#         npm run test -- --coverage
    
#     - name: Upload Test Coverage
#       if: github.event_name == 'push'
#       uses: actions/upload-artifact@v1
#       with:
#         name: test-coverage
#         path: coverage
      
#     - name: Upload Artifact
#       uses: actions/upload-artifact@v3
#       with:
#           path: build
#           name: build-files

    - name: Tests
      run: npm run test -- --coverage
     
    - name: Upload Test Coverage
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: tests
        path: coverage
    - name: Build 
      if: github.event_name == 'push'
      run: npm run build
    - name: Upload Build
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  
    - name: Build the Docker image
      run: |
         docker build -t my-react-app -f Dockerfile-prod.


    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push my-react-app
#     - name: Deploy
#       run: |
#         git config --global user.name $user_name
#         git config --global user.email $user_email
#         git remote set-url origin https://${github_token}@github.com/${repository}
#         npm run deploy
#       env:
#         user_name: 'github-actions[bot]'
#         user_email: 'github-actions[bot]@users.noreply.github.com'
#         github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#         repository: ${{ github.repository }}
